### ISSUE TITLE
性能相关问题

### ISSUE THREAD

**Issue by WonYuHao** [usr922/wseg#1]
作者您好，我是一名大四在读本科生，毕设主题是弱监督语义分割。我在拜读您的文章Weakly Supervised Semantic Segmentation by Pixel-to-Prototype Contrast后受到了很大的启发，但是在实际运行的时候遇到了一定的困难，希望您能为我解答疑惑。
1.我完全按照您提供的README指导，运行您在GitHub中上传的代码，但是在实现
“Step1: Initial Seed Generation with Contrastive Learning.”
过程中种子点的mIoU只能**达到54.6%左右**，明显低于您在**文章中提到的61.5%性能**。
下图是我截取的输出结果
![image](https://user-images.githubusercontent.com/103939254/163815044-e6306cff-bc89-45e9-b76a-ef54c73f5998.png)
2.此外，我还尝试修改了您训练部分的代码，删去了其中Cross-view Contrast部分的功能，仅保留了Intra-view Contrast部分，得到的mIoU**为55.8%**，高于在同样环境下您的原始代码所得到的结果，如此来看Cross-view Contrast反而**降低了性能**，这也是我现在不能理解的部分。
下图是我截取的只保留intra-view contrast部分得到的输出结果
![image](https://user-images.githubusercontent.com/103939254/163816481-37acf45d-2ada-43bc-9c9a-dc2a8948f6df.png)

我的系统环境为python3.6 pytorch1.10.1 CUDA10.2 符合您在README中提到的要求
硬件条件为GeForce GTX 1080 ti  12G显存
希望您能帮我解答上述两个疑惑，十分感谢！

**Comment by pigcv** [comment]
你好，你可以提供一下训练log看一下。文中报告的是三次运行的中位数，目前我也无法判断是哪里的问题。我没有跑过只用Intra-不用Cross-的性能，我是先做的Cross- 后来又加的Intra-。我的实验中，Cross的涨点是最明显的。

**Comment by usr922** [comment]
你好，你可以提供训练log看一下。文中报告的是三次运行的中位数值，目前我也无法判断哪里出错了。我没有试过只有intra-不用cross-。我的实验中是先做的cross-后加的intra-，cross-的涨点是最明显的

**Comment by usr922** [comment]
@WonYuHao  你好，你可以提供训练log看一下。文中报告的是三次运行的中位数值，目前我也无法判断哪里出错了。我没有试过只有intra-不用cross-。我的实验中是先做的cross-后加的intra-，cross-的涨点是最明显的

**Comment by WonYuHao** [comment]
>
@usr922 感谢您的回复，这是训练log，麻烦您了！

[wseg_1.log](https://github.com/usr922/wseg/files/8506420/wseg_1.log)

**Comment by usr922** [comment]
你好，我发现你使用的预训练权重是：'weights': 'model/seam_contrast.pth'。这是我提供的训练好的模型。我们应该使用ImageNet上预训练的Wide ResNet-38, 即ilsvrc-cls_rna-a1_cls1000_ep-0001.params。
另外一点小区别是，我使用了bs=9，with 3 RTX2080Ti Card。SEAM原作者使用了4 * 12G。我复现的SEAM baseline也用了3*11 GB。
其余设置应该都是一致的，如果你有其他问题，欢迎指出~

**Comment by usr922** [comment]
@WonYuHao  你好，我发现你使用的预训练权重是：'weights': 'model/seam_contrast.pth'。这是我提供的训练好的模型。我们应该使用ImageNet上预训练的Wide ResNet-38, 即ilsvrc-cls_rna-a1_cls1000_ep-0001.params。
另外一点小区别是，我使用了bs=9，with 3 RTX2080Ti Card。SEAM原作者使用了4 * 12G。我复现的SEAM baseline也用了3*11 GB。
其余设置应该都是一致的，如果你有其他问题，欢迎指出~

**Comment by usr922** [comment]
> > 
> 
> @usr922 感谢您的回复，这是训练log，麻烦您了！
> 
> [wseg_1.log](https://github.com/usr922/wseg/files/8506420/wseg_1.log)

**Comment by WonYuHao** [comment]
@usr922 感谢您的回复，我会再做尝试的
