### ISSUE TITLE
pseudo mask IoU after rw

### ISSUE THREAD

**Issue by BinghaoLu** [usr922/wseg#2]
Hi, thank you for your work on this paper and code, when I was implementing your code of random walk on the CAM, the generated pseudo mask IoU is less than 60% following the instruction, is there something that I missed?

**Comment by usr922** [comment]
Hi @BinghaoLu , thanks for your attention. What about score curve of the CAM generated by step1? The pseudo labels are evaluated on train set and the segmentation model is retrained on train+aug set. You can follow the original repo (https://github.com/jiwoon-ahn/psa) of AffinityNet for more details :)
