### ISSUE TITLE
What are la_crf and ha_crf?

### ISSUE THREAD

**Issue by IJS1016** [usr922/wseg#5]
Hi, I want to reproduce your paper.

I have completed the implementation by Step2-Preparation.
I just got some crf files as np format(crf/4.00/...), **but**, they are not split la_crf_dir, ha_crf_dir.
I don't know what la, ha. What mean of la and ha??
What should I type in $your_la_crf_dir and $your_ha_crf_dir?

Additional , I can not open crf outputs download link, (Step2: Refine with AffinityNet. - Preparation.)
(https://github.com/usr922/wseg/blob/master).

I'd appreciate it if you answered.

**Comment by usr922** [comment]
Hi, la and ha mean 'low_alpha' and 'high_alpha', and this is the same as psa (https://github.com/jiwoon-ahn/psa) and seam. The crf outputs is too large (~tens of gb), I will upload it to BaiduDrive.

**Comment by shifan-Z** [comment]
Thanks for posting your excellent code!
I met the same problem. So what should I type in $your_la_crf_dir and $your_ha_crf_dir?
I can only found crf files as np format, the path is  crf_alpha_dir/4.00/0.npy....

**Comment by shifan-Z** [comment]
> Hi, I want to reproduce your paper.
> 
> I have completed the implementation by Step2-Preparation. I just got some crf files as np format(crf/4.00/...), **but**, they are not split la_crf_dir, ha_crf_dir. I don't know what la, ha. What mean of la and ha?? What should I type in $your_la_crf_dir and $your_ha_crf_dir?
> 
> Additional , I can not open crf outputs download link, (Step2: Refine with AffinityNet. - Preparation.) (https://github.com/usr922/wseg/blob/master).
> 
> I'd appreciate it if you answered.

So could you solve the problem?

**Comment by IJS1016** [comment]
> > Hi, I want to reproduce your paper.
> > I have completed the implementation by Step2-Preparation. I just got some crf files as np format(crf/4.00/...), **but**, they are not split la_crf_dir, ha_crf_dir. I don't know what la, ha. What mean of la and ha?? What should I type in $your_la_crf_dir and $your_ha_crf_dir?
> > Additional , I can not open crf outputs download link, (Step2: Refine with AffinityNet. - Preparation.) (https://github.com/usr922/wseg/blob/master).
> > I'd appreciate it if you answered.
> 
> So could you solve the problem?

I found that la_crf value is 4.0 and ha_crf value is 24 at AffinityNet paper.

Pixel to Prototype Paper said la_crf, ha_crf value from SEAM.
SEAM Paper said these values from AffinityNet.

**Comment by shifan-Z** [comment]
> > > Hi, I want to reproduce your paper.
> > > I have completed the implementation by Step2-Preparation. I just got some crf files as np format(crf/4.00/...), **but**, they are not split la_crf_dir, ha_crf_dir. I don't know what la, ha. What mean of la and ha?? What should I type in $your_la_crf_dir and $your_ha_crf_dir?
> > > Additional , I can not open crf outputs download link, (Step2: Refine with AffinityNet. - Preparation.) (https://github.com/usr922/wseg/blob/master).
> > > I'd appreciate it if you answered.
> > 
> > 
> > So could you solve the problem?
> 
> I found that la_crf value is 4.0 and ha_crf value is 24 at AffinityNet paper.
> 
> Pixel to Prototype Paper said la_crf, ha_crf value from SEAM. SEAM Paper said these values from AffinityNet.

Thank you so much!
