### ISSUE TITLE
Question about segmentation on SEAM with deeplabv1

### ISSUE THREAD

**Issue by Shield9999** [usr922/wseg#7]
Thanks for your great work! 
I'm running code in segmentation part using SEAM deeplabv1. As I understand the wSEAM file is the from
SEAM github. However, in segmentation/experiment/SEAM_deeplabv1_resnet38/net/deeplabv1.py, I couldn't
find the wSEAM.utils file for importing "NETS".

Is there any advice or answer?

**Comment by usr922** [comment]
Thanks for the attention. That's a bug and I have fixed it.

**Comment by Shield9999** [comment]
Sorry author. I have additional question. 
I understand that the wSEAM is from SEAM github. However there was no utils file in wSEAM. 
So I can't take the wSEAM.utils file. Is there any link or file about wSEAM and wEPS?
